

// const accountingData = [
//   {
//     "field1": "Accounting",
//     "field2": "Irvine,",
//     "field3": "",
//     "field4": "sales@basis365.com",
//     "field5": "10 -- 49",
//     "field6": "",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$1,000+",
//     "field9": "Basis 365 Accounting",
//     "field10": "+1 855.236.5669 X711",
//     "field11": "https://clutch.co/profile/basis-365-accounting",
//     "field12": "9 reviews",
//     "field13": "4.8",
//     "field14": "Financial Accounting:50%\r\nBookkeeping:45%\r\nTax & Payroll Preparation:5%\r\nFinancial Accounting:50%\r\nFinancial Accounting:50%",
//     "field15": "CA",
//     "field16": "Collaborative, Cloud-based Accountants",
//     "field17": "https://www.basis365.com/basis-365-accounting-on-clutch",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Accounting",
//     "field2": "Los Angeles,",
//     "field3": "",
//     "field4": "ken@westside.tax",
//     "field5": "2 -- 9",
//     "field6": "&lt; $25",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$1,000+",
//     "field9": "Westside Tax",
//     "field10": "424-835-0232",
//     "field11": "https://clutch.co/profile/westside-tax",
//     "field12": "1 review",
//     "field13": "5",
//     "field14": "Financial Accounting:60%\r\nTax & Payroll Preparation:30%\r\nBookkeeping:10%\r\nFinancial Accounting:60%\r\nFinancial Accounting:60%",
//     "field15": "CA",
//     "field16": "Working to bring financial stability and success",
//     "field17": "http://westside.tax",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Accounting",
//     "field2": "San Francisco,",
//     "field3": "",
//     "field4": "tteale@rina.com",
//     "field5": "50 -- 249",
//     "field6": "$150 - $199",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$1,000+",
//     "field9": "RINA Accountancy Corporation",
//     "field10": "415.777.4488",
//     "field11": "https://clutch.co/profile/rina-accountancy-corporation",
//     "field12": "",
//     "field13": "",
//     "field14": "Financial Accounting:25%\r\nBookkeeping:25%\r\nForensic/Expert Witness:25%\r\nTax & Payroll Preparation:25%\r\nFinancial Accounting:25%\r\nFinancial Accounting:25%",
//     "field15": "CA",
//     "field16": "Engage the Future.",
//     "field17": "http://www.rina.com/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Accounting",
//     "field2": "New York,",
//     "field3": "",
//     "field4": "cpas@rmsbg.com",
//     "field5": "50 -- 249",
//     "field6": "$150 - $199",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$1,000+",
//     "field9": "RotenbergMeril",
//     "field10": "212.660.0050",
//     "field11": "https://clutch.co/profile/rotenbergmeril",
//     "field12": "",
//     "field13": "",
//     "field14": "Financial Accounting:30%\r\nForensic/Expert Witness:30%\r\nBookkeeping:20%\r\nTax & Payroll Preparation:20%\r\nFinancial Accounting:30%\r\nFinancial Accounting:30%",
//     "field15": "NY",
//     "field16": "Certified Public Accountants NY and NJ.",
//     "field17": "http://www.rmsbg.com/",
//     "field18": "",
//     "field19": ""
//   },
//
//   {
//     "field1": "Market Research",
//     "field2": "San Francisco,",
//     "field3": "",
//     "field4": "owen@stanventures.com",
//     "field5": "50 -- 249",
//     "field6": "",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "Undisclosed",
//     "field9": "Stan Ventures",
//     "field10": "+1 415 365 9654",
//     "field11": "https://clutch.co/profile/stan-ventures",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:20%\r\nMarketing Strategy:60%\r\nOther Marketing:20%",
//     "field15": "CA",
//     "field16": "Spirit Of Excellence",
//     "field17": "http://www.stanventures.com",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Market Research",
//     "field2": "Alameda,",
//     "field3": "",
//     "field4": "info@absolutdata.com",
//     "field5": "250 -- 999",
//     "field6": "$100 - $149",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$10,000+",
//     "field9": "Absolutdata Analytics",
//     "field10": "+1.510.748.9922",
//     "field11": "https://clutch.co/profile/absolutdata-analytics",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:10%\r\nBI & Big Data Consulting & SI:25%\r\nIoT Development:25%\r\nArtificial Intelligence:25%\r\nManagement Consulting:15%",
//     "field15": "CA",
//     "field16": "INTELLIGENT ANALYTICS. INTELLIGENTLY DELIVERED.",
//     "field17": "https://www.absolutdata.com/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Market Research",
//     "field2": "Los Angeles,",
//     "field3": "",
//     "field4": "teamdk@digitalkarma.io",
//     "field5": "2 -- 9",
//     "field6": "$100 - $149",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$5,000+",
//     "field9": "Digital Karma",
//     "field10": "424.231.5974",
//     "field11": "https://clutch.co/profile/digital-karma",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:25%\r\nMarketing Strategy:25%\r\nUX/UI Design:25%\r\nProduct Design:25%",
//     "field15": "CA",
//     "field16": "Let's Go From Concept to Reality",
//     "field17": "http://digitalkarma.io/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Market Research",
//     "field2": "Santa Clara,",
//     "field3": "",
//     "field4": "info@informaticsoutsourcing.com",
//     "field5": "2 -- 9",
//     "field6": "&lt; $25",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$1,000+",
//     "field9": "Informatics Outsourcing",
//     "field10": "1.914465511132",
//     "field11": "https://clutch.co/profile/informatics-outsourcing",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:20%\r\nNon-Voice BPO/Back Office Services:60%\r\nCustom Software Development:20%",
//     "field15": "CA",
//     "field16": "Santa Clara Outsourcing Service Provider",
//     "field17": "http://www.informaticsoutsourcing.com/index.php",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Market Research",
//     "field2": "Pasadena,",
//     "field3": "",
//     "field4": "hello@farmdesign.net",
//     "field5": "2 -- 9",
//     "field6": "$150 - $199",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$5,000+",
//     "field9": "Farm Design",
//     "field10": "626.792.9565",
//     "field11": "https://clutch.co/profile/farm-design",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:15%\r\nPackaging Design:20%\r\nGraphic Design:20%\r\nLogo:15%\r\nPrint Design:15%\r\nWeb Design:15%",
//     "field15": "CA",
//     "field16": "Cultivating Brands",
//     "field17": "http://www.farmdesign.net/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Market Research",
//     "field2": "Seattle,",
//     "field3": "",
//     "field4": "info@cofen.com",
//     "field5": "10 -- 49",
//     "field6": "$100 - $149",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$10,000+",
//     "field9": "Cocker Fennessy",
//     "field10": "206.652.9506",
//     "field11": "https://clutch.co/profile/cocker-fennessy",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:25%\r\nPublic Relations:75%",
//     "field15": "WA",
//     "field16": "Seattle Public Affairs Firm",
//     "field17": "http://www.cofen.com/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Market Research",
//     "field2": "Sacramento,",
//     "field3": "",
//     "field4": "trainsbury@randlecommunications.com",
//     "field5": "10 -- 49",
//     "field6": "$100 - $149",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$10,000+",
//     "field9": "Randle Communications",
//     "field10": "916.448.5802",
//     "field11": "https://clutch.co/profile/randle-communications",
//     "field12": "",
//     "field13": "",
//     "field14": "Market Research:20%\r\nMarketing Strategy:35%\r\nMedia Planning & Buying:30%\r\nPublic Relations:15%",
//     "field15": "CA",
//     "field16": "Public Relations & Public Affairs",
//     "field17": "http://www.randlecommunications.com/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "media buying",
//     "field2": "New York,",
//     "field3": "",
//     "field4": "connect.talent@genpact.com",
//     "field5": "10,000+",
//     "field6": "&lt; $25",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$1,000+",
//     "field9": "Genpact",
//     "field10": "+1.212.896.6600",
//     "field11": "https://clutch.co/profile/genpact",
//     "field12": "",
//     "field13": "",
//     "field14": "Media Planning & Buying:10%\r\nNon-Voice BPO/Back Office Services:30%\r\nIT Managed Services:20%\r\nArtificial Intelligence:20%\r\nFinancial Accounting:10%\r\nHR Consulting & Outsourcing:10%",
//     "field15": "NY",
//     "field16": "New York Global Professional Services",
//     "field17": "http://www.genpact.com/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Mobile App Developers",
//     "field2": "San Francisco ,",
//     "field3": "",
//     "field4": "hello+clutch@arctouch.com",
//     "field5": "50 -- 249",
//     "field6": "$100 - $149",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$25,000+",
//     "field9": "ArcTouch",
//     "field10": "415.944.2000",
//     "field11": "https://clutch.co/profile/arctouch",
//     "field12": "12 reviews",
//     "field13": "4.9",
//     "field14": "Mobile App Development:50%\r\nBlockchain:30%\r\nUX/UI Design:20%",
//     "field15": "CA",
//     "field16": "Mobile Apps & Connected Experiences",
//     "field17": "https://arctouch.com/?utm_source=clutch&utm_medium=referral&utm_campaign=listings&utm_content=main%20link",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Mobile App Developers",
//     "field2": "Palo Alto,",
//     "field3": "",
//     "field4": "info@intellectsoft.net",
//     "field5": "250 -- 999",
//     "field6": "$50 - $99",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$25,000+",
//     "field9": "Intellectsoft",
//     "field10": "650 300 4335",
//     "field11": "https://clutch.co/profile/intellectsoft",
//     "field12": "22 reviews",
//     "field13": "4.8",
//     "field14": "Mobile App Development:50%\r\nCustom Software Development:25%\r\nBlockchain:25%",
//     "field15": "CA",
//     "field16": "Developing serious software solutions",
//     "field17": "http://intellectsoft.net/?utm_source=clutch.co&utm_medium=referral&utm_campaign=mobile_dev",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Mobile App Developers",
//     "field2": "San Francisco,",
//     "field3": "",
//     "field4": "Clutch-Enquiries@appsterhq.com",
//     "field5": "250 -- 999",
//     "field6": "$50 - $99",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$25,000+",
//     "field9": "Appster",
//     "field10": "844.277.7837",
//     "field11": "https://clutch.co/profile/appster",
//     "field12": "20 reviews",
//     "field13": "4.8",
//     "field14": "Mobile App Development:55%\r\nWeb Development:25%\r\nCustom Software Development:15%\r\nUX/UI Design:5%",
//     "field15": "CA",
//     "field16": "The App Developer for Startups & Challenger Brands",
//     "field17": "http://AppsterHQ.com",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Mobile App Developers",
//     "field2": "New York,",
//     "field3": "",
//     "field4": "info@mobikasa.com",
//     "field5": "10 -- 49",
//     "field6": "$50 - $99",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$10,000+",
//     "field9": "MOBIKASA",
//     "field10": "+1 646-880-4504",
//     "field11": "https://clutch.co/profile/mobikasa",
//     "field12": "39 reviews",
//     "field13": "4.7",
//     "field14": "Mobile App Development:55%\r\nWeb Development:45%",
//     "field15": "NY",
//     "field16": "Awesome Mobile Apps & Web Development",
//     "field17": "https://www.mobikasa.com/services/mobile-app-development/",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Mobile App Developers",
//     "field2": "Sunnyvale,",
//     "field3": "",
//     "field4": "getstarted@intuz.com",
//     "field5": "50 -- 249",
//     "field6": "$25 - $49",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$10,000+",
//     "field9": "Intuz",
//     "field10": "+1 650.451.1499",
//     "field11": "https://clutch.co/profile/intuz",
//     "field12": "27 reviews",
//     "field13": "4.7",
//     "field14": "Mobile App Development:50%\r\nWeb Development:50%",
//     "field15": "CA",
//     "field16": "Custom Mobile App Development Company",
//     "field17": "https://www.intuz.com",
//     "field18": "",
//     "field19": ""
//   },
//   {
//     "field1": "Mobile App Developers",
//     "field2": "Sunnyvale,",
//     "field3": "",
//     "field4": "sales@algoworks.com",
//     "field5": "50 -- 249",
//     "field6": "$25 - $49",
//     "field7": "https://static1.clutch.co/sites/all/modules/contrib/lazyloader/image_placeholder.gif",
//     "field8": "$5,000+",
//     "field9": "Algoworks",
//     "field10": "+1.877.284.1028",
//     "field11": "https://clutch.co/profile/algoworks",
//     "field12": "22 reviews",
//     "field13": "5",
//     "field14": "Mobile App Development:80%\r\nCRM Consulting and SI:20%",
//     "field15": "CA",
//     "field16": "Go Mobile. Go Cloud. Go Digital.",
//     "field17": "https://goo.gl/tMJjd6",
//     "field18": "",
//     "field19": ""
//   }
//
// ]

var arrayTest = [
  {"name": "Joe", "age": 17},
  {"name": "Bob", "age": 17},
  {"name": "Carl", "age": 35}
];



// module.exports = accountingData, arrayTest
module.exports =  arrayTest
